"use client";

import Link from "next/link";
import { useState } from "react";
import { Check, Sparkles, WandSparkles } from "lucide-react";

type Brief = { summary: string; priorities: Array<{ leadId: string; company: string; reason: string; action: string }>; risks: string[]; wins: string[] };

export function DailyBrief() {
  const [brief, setBrief] = useState<Brief | null>(null); const [pending, setPending] = useState(false); const [warning, setWarning] = useState(""); const [saved, setSaved] = useState(false);
  async function generate() { setPending(true); setWarning(""); setSaved(false); const response = await fetch("/api/ai/daily-brief", { method: "POST" }); const payload = await response.json(); if (response.ok) { setBrief(payload.data); setWarning(payload.warning ?? ""); } else setWarning(payload.error?.message ?? "The brief could not be generated."); setPending(false); }
  async function save() { if (!brief) return; const response = await fetch("/api/ai/results", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ useCase: "DAILY_BRIEF", model: warning ? "rules-fallback-v1" : "gemini-3.5-flash-lite", result: brief }) }); setSaved(response.ok); }
  return <div className="page"><header className="page-head"><div><span className="eyebrow">Gemini sales copilot</span><h1>Your day, made clearer.</h1><p className="lede">A structured brief grounded in pipeline facts—not invented certainty.</p></div><button className="button" onClick={generate} disabled={pending}><WandSparkles size={16} />{pending ? "Building brief…" : brief ? "Refresh brief" : "Create today’s brief"}</button></header>
    <section className="ai-shell"><div className="ai-kicker"><Sparkles size={15} />Daily sales brief</div>{!brief && <div className="empty"><strong>Ready when you are.</strong>Vaada will rank current priorities, flag risks, and surface progress. Only necessary CRM context is sent to Gemini.</div>}{warning && <p className="notice" role="status">{warning}</p>}{brief && <div className="ai-output"><h2>{brief.summary}</h2><div className="divider" /><div className="grid ai-grid"><section><h3>Priority conversations</h3><div className="attention-list">{brief.priorities.map((item, index) => <Link href={`/leads/${item.leadId}`} className="attention-row" style={{ gridTemplateColumns: "28px 1fr" }} key={`${item.leadId}-${index}`}><span className="badge">{index + 1}</span><div><strong>{item.company}</strong><div className="subtle">{item.reason}</div><p style={{ margin: "8px 0 0", fontSize: 13 }}>{item.action}</p></div></Link>)}</div></section><section><h3>Risks to watch</h3><ul>{brief.risks.map((item) => <li key={item}>{item}</li>)}</ul><h3 style={{ marginTop: 24 }}>Momentum</h3><ul>{brief.wins.map((item) => <li key={item}>{item}</li>)}</ul></section></div><div className="dialog-actions"><button className="button secondary" onClick={save}><Check size={14} />{saved ? "Saved" : "Save this brief"}</button></div></div>}</section>
    <section className="grid metrics" style={{ marginTop: 20 }}><article className="metric"><span>Context policy</span><strong style={{ fontSize: 19 }}>Minimum necessary</strong><small>No phone or email in insight/brief requests</small></article><article className="metric"><span>Output contract</span><strong style={{ fontSize: 19 }}>Validated JSON</strong><small>Rejected if fields or lead IDs are invalid</small></article><article className="metric"><span>Failure mode</span><strong style={{ fontSize: 19 }}>Useful fallback</strong><small>Rules-based attention list stays available</small></article><article className="metric"><span>Human control</span><strong style={{ fontSize: 19 }}>Review first</strong><small>Drafts remain editable and unsent</small></article></section>
  </div>;
}
